events {
    worker_connections 1024;
}

http {
    upstream frontend_app {
        server frontend:80;
    }

    upstream backend_app {
        server backend:3000;
    }

    server {
        listen 80;

        # Redirigir peticiones del frontend
        location / {
            proxy_pass http://frontend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirigir llamadas API al backend
        location /api/ {
            proxy_pass http://backend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}